import cv2
import numpy as np
from matplotlib import pyplot as plt
img_path = "C:/Users/Alireza Sarve Niazi/Desktop/data/Mct2.jpg"
#img_path = "C:/Users/Alireza Sarve Niazi/Desktop/data/G_Heart.jpg"
#img_path = "C:/Users/Alireza Sarve Niazi/Desktop/data/nemo.png"
img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(img)binary inv
plt.show() 
img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE) 
_, mask = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY_INV)
kernal = np.ones((5,5), np.uint8)
dilation = cv2.dilate(mask,kernal, iterations =3)
erosion = cv2.erode(mask,kernal, iterations =7)
opening = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernal)
closing = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernal)
mg = cv2.morphologyEx(mask, cv2.MORPH_GRADIENT, kernal)
th = cv2.morphologyEx(mask, cv2.MORPH_TOPHAT, kernal)
titles = ['image', 'mask', 'dialation', 'erosion', 'opening', 'closing', 'mg', 'th']
images = [img, mask, dilation, erosion, opening, closing, mg, th]
for i in range(8):
    plt.subplot(2, 4, i+1), plt.imshow(images[i], 'gray')
    plt.title(titles[i])
    plt.xticks([]), plt.yticks([])
#plt.imshow(img)
plt.show()
#print(img.shape) 
